# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lars Tijhuis blog
email: ljtijhuis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This is the personal blog of Lars Tijhuis, sharing posts on my life as an IT guy who loves to nerd around and to travel! I am currently employed at KPMG in the Netherlands, where I focus on cloud, IT infrastructure and architecture, and software (quality) related assignments. I've set-up this blog to get myself motivated to share my work! And my holiday stories as well.. Enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lars.tijhuis.blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: larstijhuis
github_username:  ljtijhuis

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
